package com.timwoodcreates.roost;

import com.google.common.collect.ImmutableSet;

import java.util.Set;

public class RoostTextures {
    public static Set<String> stockTextures = ImmutableSet.of(
     /* could add goldenchicken or hen_golden,
     redchicken or hen_red,
     and speckedchicken or hen_specked
     but brownchicken already exists, so hen_brown might not bee needed */
     /* I planned to test with amberchicken for hen_golden,
     draconiumawakenedchicken for hen_red,
     and titaniumchicken for hen_specked */
     /* currently, I have hen_[variant].png files in /textures/items/chicken
     as well as in /textures/items/animania */

            "advancedprocessorchicken",
            "aluminumchicken",
            "amberchicken",
            "amethystchicken",
            "arditechicken",
            "basalzrodchicken",
            "basicprocessorchicken",
            "blackchicken",
            "blackquartzchicken",
            "blazechicken",
            "blitzrodchicken",
            "blizzrodchicken",
            "bloodslime",
            "bluechicken",
            "blueslime",
            "blutoniumchicken",
            "boopbeepchick",
            "brasschicken",
            "bronzechicken",
            "brownchicken",
            "bulletchicken",
            "cablechicken",
            "chickenosto",
            "chromechicken",
            "cinnabarchicken",
            "claychicken",
            "coalchicken",
            "cobaltchicken",
            "conductiveironchicken",
            "constantanchicken",
            "constructioncorechicken",
            "copperchicken",
            "cupronickelchicken",
            "cyanchicken",
            "cyanitechicken",
            "darkgemchicken",
            "darksteelchicken",
            "demonmetalchicken",
            "destructioncorechicken",
            "diamantinecrystalchicken",
            "diamondchicken",
            "draconiumawakenedchicken",
            "draconiumchicken",
            "electricalsteelchicken",
            "electrumchicken",
            "elementiumchicken",
            "emeradiccrystalchicken",
            "emeraldchicken",
            "enderchicken",
            "enderiumchicken",
            "energeticalloychicken",
            "enoricrystalchicken",
            "flintchicken",
            "funwaychick",
            "garnetchicken",
            "ghastchicken",
            "glasschicken",
            "glowstonechicken",
            "goldchicken",
            "graphitechicken",
            "graychicken",
            "greenchicken",
            "gunpowderchicken",
            "improvedprocessorchicken",
            "invarchicken",
            "iridiumchicken",
            "ironchicken",
            "knightslimechicken",
            "lavachicken",
            "leadchicken",
            "leatherchicken",
            "lightbluechicken",
            "limechicken",
            "logchicken",
            "ludicritechicken",
            "lumiumchicken",
            "lunarreactivedustchicken",
            "magentachicken",
            "magicalwoodchicken",
            "magmachicken",
            "magmaslime",
            "malachitechicken",
            "manasteelchicken",
            "manyullynchicken",
            "mithrilchicken",
            "moonstonechicken",
            "mramericanchick",
            "netherwartchicken",
            "nickelchicken",
            "obsidianchicken",
            "orangechicken",
            "osmiumchicken",
            "paliscrystalchicken",
            "pcrystalchicken",
            "peridotchicken",
            "pigironchicken",
            "pinkchicken",
            "pinkslimechicken",
            "platinumchicken",
            "pshardchicken",
            "pulsatingironchicken",
            "purplechicken",
            "purpleslime",
            "quartzchicken",
            "quartzenrichedironchicken",
            "redchicken",
            "redstonealloychicken",
            "redstonechicken",
            "redstonecrystalchicken",
            "refinedironchicken",
            "restoniacrystalchicken",
            "richslagchicken",
            "rubberchicken",
            "rubychicken",
            "saltchicken",
            "saltpeterchicken",
            "sandchicken",
            "sapphirechicken",
            "signalumchicken",
            "siliconchicken",
            "silverdyechicken",
            "silverorechicken",
            "slagchicken",
            "slimechicken",
            "smartchicken",
            "snowballchicken",
            "soulariumchicken",
            "soulsandchicken",
            "steelchicken",
            "stoneburntchicken",
            "stringchicken",
            "sulfurchicken",
            "tanzanitechicken",
            "terrasteelchicken",
            "tinchicken",
            "titaniumchicken",
            "topazchicken",
            "tungstenchicken",
            "tungstensteelchicken",
            "unknownchicken",
            "uraniumchicken",
            "vanilla",
            "vibrantalloychicken",
            "vinteumchicken",
            "voidcrystalchicken",
            "waterchicken",
            "whitechicken",
            "xpchicken",
            "yelloriumchicken",
            "yellowchicken",
            "yellowgarnetchicken",
            "zincchicken"
 );
}
